### ISSUE TITLE
More docs/guidance re: deployment.

### ISSUE THREAD

**Issue by zenhack** [CCI-MOC/obmd#15]
We should document how to deploy obmd in common configurations. It's easy to just run the executable, but:

* We should still write a blurb about it.
* If we endorse that method in production, we should first implement TLS suppor (#14).
* Many users may want to put it behind another web server anyway, for a number of reasons including having other web/http services running on the same box -- so we should document how to do this.

**Comment by Izhmash** [comment]
While we're talking about guiding newcomers, do we want to make an `examples` folder to save an example config file that people can copy?

**Comment by naved001** [comment]
Since the configuration is pretty small at the moment, I am fine either ways (having it in the readme or having a sample in the examples directory)

**Comment by zenhack** [comment]
Yeah, I don't think we're at the point where there's enough information there for splitting it out to make sense.

**Comment by Izhmash** [comment]
Ok, sounds good then.  I'll work on the documentation after #22.

**Comment by zenhack** [comment]
#26 is merged, closing.
