### ISSUE TITLE
Pre-built binaries

### ISSUE THREAD

**Issue by zenhack** [CCI-MOC/obmd#21]
Right now, HIL's CI is building obmd from source, which requires installing a Go toolchain, which takes quite a while. One way we could speed up the process is by downloading pre-build obmd executables instead -- we wouldn't need the toolchain, and we wouldn't need to build anything, just download a single file (right now on my system obmd is ~7 MiB stripped).

There are some process questions here; it would be nice if we could automate this somehow; otherwise we run the risk of stuff getting out of sync.

//cc @naved001, @Izhmash

**Comment by naved001** [comment]
> There are some process questions here; it would be nice if we could automate this somehow; otherwise we run the risk of stuff getting out of sync.

I think we can just make a tagged release here. And when we do that there's an option to upload the binary to github. In HIL's CI, we just pin down the version of obmd to use.

**Comment by naved001** [comment]
We should be able to get the latest tagged release too, so HIL's CI will always run against that, but we won't get the latest master obviously (there will be no binary if there's no release).

**Comment by zenhack** [comment]
Works for me.

**Comment by naved001** [comment]
https://github.com/CCI-MOC/hil/pull/1019

**Comment by zenhack** [comment]
Fixed, closing.
