### ISSUE TITLE
Be a little smarter re: 'insecure' option

### ISSUE THREAD

**Issue by zenhack** [CCI-MOC/obmd#28]
@naved001's pr with the install guide uses the `Insecure` option as part of the setup involving apache. While this is reasonable, I'd prefer not to have that option be something users use routinely. One idea: we could perhaps allow this to be omitted if the server is only listening on `127.0.0.1`. Thoughts?

//cc @naved001, @ianballou

**Comment by naved001** [comment]
What if someone decides to run obmd on a private network they trust? And what if someone is using OBMd for development?

**Comment by zenhack** [comment]
For the latter case I don't think the above would normally cause a problem. But we could still have an insecure option, I'm just suggesting maybe allowing it to be omitted if the server is only listening on the loopback interface.

**Comment by naved001** [comment]
> But we could still have an insecure option, I'm just suggesting maybe allowing it to be omitted if the server is only listening on the loopback interface.

That sounds reasonable to me.

**Comment by zenhack** [comment]
Quoting Ian Ballou (2018-10-16 10:26:45)

>    So you mean that if the address is set to localhost and there is no
>    Insecure in the config, then the default will be Insecure = true?

I'd say only 127.0.0.1, not just localhost (the later can theoretically
actually do a DNS lookup), but yes, basically.

**Comment by ianballou** [comment]
Ok sure, that sounds like it makes sense to me then.
