### ISSUE TITLE
Transfer repository to the CCI-MOC organization.

### ISSUE THREAD

**Issue by zenhack** [CCI-MOC/obmd#5]
It probably doesn't make a ton of sense for this repo to be under my user account; we ought to transfer it to the CCI-MOC org. Probably someone with owner access for CCI-MOC will have to hit accept; who has that access these days?

//cc @naved001

**Comment by naved001** [comment]
@pns005 is owner on CCI-MOC org. Can you start with the transfer request, and I'll tell her to accept it.

**Comment by naved001** [comment]
let me know in the comments here when you do that, and I'll tell her to accept it on her end.

**Comment by zenhack** [comment]
Ok, done. There doesn't seem to be a way to request transfer to an organization directly unless you have access to it, so I requested transfer to @pns005; she'll have to move it to the organization account after accepting.

**Comment by pns005** [comment]
Just accepted...

**Comment by zenhack** [comment]
Cool. You'll have to go to the repo's settings and transfer it again to cci-moc.

**Comment by pns005** [comment]
Transferred to CCI-MOC. You, Ian, and Naved are the 'Admin' of
CCI-MOC/obmd.

Have fun!
Piyanai
