### ISSUE TITLE
Postgres support

### ISSUE THREAD

**Issue by zenhack** [CCI-MOC/obmd#7]
Right now we have sqlite as the only supported database. Adding others will be trivial, and we probably want to; at least postgres would be a good idea.

This would be a good easy task for someone still getting acquainted with Go.

//cc @naved001, @Izhmash, @xuhang57

**Comment by Izhmash** [comment]
In this case, would the database selection be in the config file?

**Comment by Izhmash** [comment]
I'll start working on this, should help me get a handle on Go.

**Comment by zenhack** [comment]
@Izhmash, great.

Right now the database info is passed via a command line flag:

https://github.com/CCI-MOC/obmd/blob/master/main.go#L28

But I actually think the config file would be better. You'd have to add another option to specifiy the driver, which is currently hard-coded as sqlite:

https://github.com/CCI-MOC/obmd/blob/master/main.go#L59

**Comment by Izhmash** [comment]
I have a quick prototype here: https://github.com/CCI-MOC/obmd/compare/master...Izhmash:postgres-support. My solution is to add two fields to the config, one for the DB type and one for the DB URI. 
Do you think this approach works ok? I'll add documentation, type-checking, and tests(?) in the real PR.

**Comment by zenhack** [comment]
Yeah, this looks reasonable. Re: formatting, I assume you've got your editor set up to use spaces for indentation. The Go convention is to use tabs.

The Go style guide amounts to "run `gofmt`". I highly recommend setting up you editor to do so automatically.

**Comment by naved001** [comment]
#10
